export const sampleRecords = {
  '0nLa1lqws0bxl0d19d3X': {
    all_double_speed: false,
    all_normal_speed: true,
    comment: 'キノコ死す',
    creatable_with_explosion: true,
    created_at: {
      seconds: 1577582806,
      nanoseconds: 204000000
    },
    exp_per_turn: 36.46572170249,
    inp: {
      config: {
        trial: 100,
        turn: 1500
      },
      friends: [
        {
          double_speed: false,
          hp_dope: 0,
          lv: 3,
          name: 'おばけキノコ',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 30,
          name: 'ホイミスライム',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 30,
          name: 'スモールグール',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 30,
          name: 'ホイミスライム',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        }
      ],
      map: {
        col: 10,
        data: [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          10,
          19,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          11,
          12,
          13,
          14,
          1,
          1,
          1,
          1,
          1,
          9,
          9,
          9,
          9,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          15,
          16,
          17,
          18,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        row: 10
      }
    },
    lv_kinoko: 3,
    lv_kiton: 0,
    num_hoimi_slime: 2,
    num_killer_machine: 6,
    stopped_by_enemy_genocide: 0,
    stopped_by_friend_kill: 20,
    turn_passed: 82.30333333333333,
    userid: 'jhOByTg5QfWbuon3iQ3a09k6hO33',
    username: '怒りの',
    with_kinoko: true,
    with_kiton: false
  },
  '6CPGCwmLSsCnMAw4Q7ah': {
    all_double_speed: true,
    all_normal_speed: false,
    comment: '71F_倍速5:5_ポケットなし_処理キラ1弱',
    creatable_with_explosion: true,
    created_at: {
      seconds: 1577600597,
      nanoseconds: 737000000
    },
    exp_per_turn: 106.779090061665,
    inp: {
      config: {
        trial: 300,
        turn: 1500
      },
      friends: [
        {
          double_speed: true,
          hp_dope: 0,
          lv: 89,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 88,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 80,
          lv: 59,
          name: 'きとうし',
          sealed: true,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 89,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 80,
          lv: 88,
          name: 'ホイミスライム',
          sealed: true,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 89,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 82,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 80,
          lv: 82,
          name: 'おばけキノコ',
          sealed: true,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 80,
          lv: 98,
          name: 'スモールグール',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 88,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 1,
          weaken_def: 0
        }
      ],
      map: {
        col: 10,
        data: [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          16,
          15,
          13,
          11,
          10,
          1,
          1,
          1,
          1,
          0,
          9,
          9,
          9,
          9,
          9,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          0,
          18,
          14,
          19,
          12,
          17,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        row: 10
      }
    },
    lv_kinoko: 82,
    lv_kiton: 59,
    num_hoimi_slime: 1,
    num_killer_machine: 6,
    stopped_by_enemy_genocide: 48,
    stopped_by_friend_kill: 0,
    turn_passed: 71.06888888888888,
    userid: 'hpnLmiGhLlcJkiKdumqcw24gf7s1',
    username: 'くさパン',
    with_kinoko: true,
    with_kiton: true
  },
  LtSfnJ9r7uqfX1ouwghG: {
    all_double_speed: false,
    all_normal_speed: true,
    comment: 'test desu !',
    creatable_with_explosion: false,
    created_at: {
      seconds: 1577531087,
      nanoseconds: 553000000
    },
    exp_per_turn: 46.30604000000001,
    inp: {
      config: {
        trial: 100,
        turn: 1500
      },
      friends: [
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 30,
          name: 'ホイミスライム',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 30,
          name: 'スモールグール',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 30,
          name: 'ホイミスライム',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        }
      ],
      map: {
        col: 10,
        data: [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          19,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          10,
          11,
          12,
          13,
          14,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          9,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          15,
          16,
          17,
          18,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        row: 10
      }
    },
    lv_kinoko: 0,
    lv_kiton: 0,
    num_hoimi_slime: 2,
    num_killer_machine: 7,
    stopped_by_enemy_genocide: 0,
    stopped_by_friend_kill: 0,
    turn_passed: 100,
    userid: 'jhOByTg5QfWbuon3iQ3a09k6hO33',
    username: '怒りの',
    with_kinoko: false,
    with_kiton: false
  },
  OfmjV0VJkpcUArz4YSHb: {
    all_double_speed: true,
    all_normal_speed: false,
    comment: '71F_倍速5:5_キートン分離',
    creatable_with_explosion: false,
    created_at: {
      seconds: 1577600294,
      nanoseconds: 719000000
    },
    exp_per_turn: 101.94795217180962,
    inp: {
      config: {
        trial: 300,
        turn: 1500
      },
      friends: [
        {
          double_speed: true,
          hp_dope: 0,
          lv: 89,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 88,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 80,
          lv: 59,
          name: 'きとうし',
          sealed: true,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 89,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 80,
          lv: 88,
          name: 'ホイミスライム',
          sealed: true,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 89,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 82,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 88,
          name: 'おばけキノコ',
          sealed: true,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 80,
          lv: 98,
          name: 'スモールグール',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 88,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        }
      ],
      map: {
        col: 10,
        data: [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          16,
          15,
          13,
          11,
          10,
          1,
          1,
          1,
          1,
          0,
          9,
          9,
          9,
          9,
          9,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          0,
          19,
          18,
          17,
          14,
          1,
          12,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        row: 10
      }
    },
    lv_kinoko: 88,
    lv_kiton: 59,
    num_hoimi_slime: 1,
    num_killer_machine: 6,
    stopped_by_enemy_genocide: 36,
    stopped_by_friend_kill: 0,
    turn_passed: 78.89755555555556,
    userid: 'hpnLmiGhLlcJkiKdumqcw24gf7s1',
    username: 'くさパン',
    with_kinoko: true,
    with_kiton: true
  },
  Ph2J9irLSykihxE2luIk: {
    all_double_speed: false,
    all_normal_speed: true,
    comment: 'aaaaa',
    creatable_with_explosion: true,
    created_at: {
      seconds: 1577584642,
      nanoseconds: 87000000
    },
    exp_per_turn: 45.505826666666664,
    inp: {
      config: {
        trial: 100,
        turn: 1500
      },
      friends: [
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 30,
          name: 'ホイミスライム',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 30,
          name: 'スモールグール',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 30,
          name: 'ホイミスライム',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        }
      ],
      map: {
        col: 10,
        data: [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          19,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          10,
          11,
          12,
          13,
          14,
          1,
          1,
          1,
          1,
          1,
          9,
          9,
          9,
          9,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          15,
          16,
          17,
          18,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        row: 10
      }
    },
    lv_kinoko: 0,
    lv_kiton: 0,
    num_hoimi_slime: 2,
    num_killer_machine: 7,
    stopped_by_enemy_genocide: 0,
    stopped_by_friend_kill: 0,
    turn_passed: 100,
    userid: 'jhOByTg5QfWbuon3iQ3a09k6hO33',
    username: '怒りの',
    with_kinoko: false,
    with_kiton: false
  },
  XSYZwURRs0mdDi5uQr9W: {
    all_double_speed: false,
    all_normal_speed: true,
    comment: '',
    creatable_with_explosion: false,
    created_at: {
      seconds: 1577521183,
      nanoseconds: 558000000
    },
    exp_per_turn: 46.46722666666665,
    inp: {
      config: {
        trial: 100,
        turn: 1500
      },
      friends: [
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 30,
          name: 'ホイミスライム',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 30,
          name: 'スモールグール',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 30,
          name: 'ホイミスライム',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        }
      ],
      map: {
        col: 10,
        data: [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          19,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          10,
          11,
          12,
          13,
          14,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          9,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          15,
          16,
          17,
          18,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        row: 10
      }
    },
    lv_kinoko: 0,
    lv_kiton: 0,
    num_hoimi_slime: 2,
    num_killer_machine: 7,
    stopped_by_enemy_genocide: 0,
    stopped_by_friend_kill: 0,
    turn_passed: 100,
    userid: 'jhOByTg5QfWbuon3iQ3a09k6hO33',
    username: '怒りの',
    with_kinoko: false,
    with_kiton: false
  },
  g4ReuuIlZZ46g1wek5Rt: {
    all_double_speed: true,
    all_normal_speed: false,
    comment: '！！！',
    creatable_with_explosion: true,
    created_at: {
      seconds: 1578676456,
      nanoseconds: 404000000
    },
    exp_per_turn: 121.34871280775975,
    inp: {
      config: {
        trial: 100,
        turn: 1500
      },
      friends: [
        {
          double_speed: true,
          hp_dope: 0,
          lv: 99,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 99,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 99,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 99,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 99,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 99,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 99,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 99,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 99,
          name: 'スモールグール',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 99,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        }
      ],
      map: {
        col: 10,
        data: [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          9,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          9,
          15,
          0,
          16,
          0,
          0,
          9,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          17,
          9,
          9,
          1,
          1,
          9,
          9,
          9,
          9,
          9,
          9,
          9,
          9,
          1,
          1,
          1,
          10,
          11,
          12,
          0,
          0,
          19,
          9,
          1,
          1,
          1,
          0,
          0,
          13,
          0,
          0,
          9,
          9,
          1,
          1,
          1,
          0,
          0,
          14,
          0,
          0,
          18,
          9,
          1,
          1,
          1,
          0,
          0,
          1,
          0,
          0,
          0,
          9,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        row: 10
      }
    },
    lv_kinoko: 0,
    lv_kiton: 0,
    num_hoimi_slime: 0,
    num_killer_machine: 9,
    stopped_by_enemy_genocide: 30,
    stopped_by_friend_kill: 65,
    turn_passed: 29.58533333333333,
    userid: 'jhOByTg5QfWbuon3iQ3a09k6hO33',
    username: '怒りの',
    with_kinoko: false,
    with_kiton: false
  },
  iQLy6ma8lpbS34XiIl0z: {
    all_double_speed: true,
    all_normal_speed: false,
    comment: '倍速スモコン',
    creatable_with_explosion: true,
    created_at: {
      seconds: 1577546619,
      nanoseconds: 888000000
    },
    exp_per_turn: 90.92453333333334,
    inp: {
      config: {
        trial: 100,
        turn: 1500
      },
      friends: [
        {
          double_speed: true,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 30,
          name: 'ホイミスライム',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 30,
          name: 'スモールグール',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 30,
          name: 'ホイミスライム',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        }
      ],
      map: {
        col: 10,
        data: [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          19,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          10,
          11,
          12,
          13,
          14,
          1,
          1,
          1,
          1,
          1,
          9,
          9,
          9,
          9,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          15,
          16,
          17,
          18,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        row: 10
      }
    },
    lv_kinoko: 0,
    lv_kiton: 0,
    num_hoimi_slime: 2,
    num_killer_machine: 7,
    stopped_by_enemy_genocide: 0,
    stopped_by_friend_kill: 0,
    turn_passed: 100,
    userid: 'jhOByTg5QfWbuon3iQ3a09k6hO33',
    username: '怒りの',
    with_kinoko: false,
    with_kiton: false
  },
  lGNb9GXX1Uo6qDAt0jQ5: {
    all_double_speed: true,
    all_normal_speed: false,
    comment: '71F_倍速5:5_ポケットなし_1',
    creatable_with_explosion: true,
    created_at: {
      seconds: 1577599622,
      nanoseconds: 146000000
    },
    exp_per_turn: 106.79432747716419,
    inp: {
      config: {
        trial: 300,
        turn: 1500
      },
      friends: [
        {
          double_speed: true,
          hp_dope: 0,
          lv: 89,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 88,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 78,
          lv: 59,
          name: 'きとうし',
          sealed: true,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 80,
          lv: 89,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 88,
          name: 'ホイミスライム',
          sealed: true,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 89,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 82,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 88,
          name: 'おばけキノコ',
          sealed: true,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 90,
          lv: 98,
          name: 'スモールグール',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 88,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        }
      ],
      map: {
        col: 10,
        data: [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          16,
          15,
          13,
          11,
          10,
          1,
          1,
          1,
          1,
          0,
          9,
          9,
          9,
          9,
          9,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          0,
          19,
          14,
          12,
          17,
          18,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        row: 10
      }
    },
    lv_kinoko: 88,
    lv_kiton: 59,
    num_hoimi_slime: 1,
    num_killer_machine: 6,
    stopped_by_enemy_genocide: 56.666666666666664,
    stopped_by_friend_kill: 0,
    turn_passed: 64.17288888888889,
    userid: 'hpnLmiGhLlcJkiKdumqcw24gf7s1',
    username: 'くさパン',
    with_kinoko: true,
    with_kiton: true
  },
  tdQP3lsWPnanjSgUIZZ8: {
    all_double_speed: false,
    all_normal_speed: true,
    comment: 'test',
    creatable_with_explosion: true,
    created_at: {
      seconds: 1577519192,
      nanoseconds: 357000000
    },
    exp_per_turn: 45.463146666666674,
    inp: {
      config: {
        trial: 100,
        turn: 1500
      },
      friends: [
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 30,
          name: 'ホイミスライム',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 30,
          name: 'スモールグール',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 30,
          name: 'ホイミスライム',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        }
      ],
      map: {
        col: 10,
        data: [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          19,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          10,
          11,
          12,
          13,
          14,
          1,
          1,
          1,
          1,
          1,
          9,
          9,
          9,
          9,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          15,
          16,
          17,
          18,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        row: 10
      }
    },
    lv_kinoko: 0,
    lv_kiton: 0,
    num_hoimi_slime: 2,
    num_killer_machine: 7,
    stopped_by_enemy_genocide: 0,
    stopped_by_friend_kill: 0,
    turn_passed: 100,
    userid: 'jhOByTg5QfWbuon3iQ3a09k6hO33',
    username: '怒りの',
    with_kinoko: false,
    with_kiton: false
  },
  upvLdcnsxcawIg1yngga: {
    all_double_speed: true,
    all_normal_speed: false,
    comment: '71F_倍速5:5_ポケットあり',
    creatable_with_explosion: false,
    created_at: {
      seconds: 1577600886,
      nanoseconds: 203000000
    },
    exp_per_turn: 100.20467111111111,
    inp: {
      config: {
        trial: 300,
        turn: 1500
      },
      friends: [
        {
          double_speed: true,
          hp_dope: 0,
          lv: 89,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 88,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 80,
          lv: 59,
          name: 'きとうし',
          sealed: true,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 89,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 80,
          lv: 88,
          name: 'ホイミスライム',
          sealed: true,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 89,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 82,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 80,
          lv: 88,
          name: 'おばけキノコ',
          sealed: true,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 80,
          lv: 98,
          name: 'スモールグール',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 88,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        }
      ],
      map: {
        col: 10,
        data: [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          16,
          15,
          13,
          11,
          10,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          9,
          9,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          18,
          19,
          14,
          17,
          12,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        row: 10
      }
    },
    lv_kinoko: 88,
    lv_kiton: 59,
    num_hoimi_slime: 1,
    num_killer_machine: 6,
    stopped_by_enemy_genocide: 0,
    stopped_by_friend_kill: 0,
    turn_passed: 100,
    userid: 'hpnLmiGhLlcJkiKdumqcw24gf7s1',
    username: 'くさパン',
    with_kinoko: true,
    with_kiton: true
  },
  yrs9MYnkRvtYLL0uEFqT: {
    all_double_speed: true,
    all_normal_speed: false,
    comment: '',
    creatable_with_explosion: false,
    created_at: {
      seconds: 1577676799,
      nanoseconds: 566000000
    },
    exp_per_turn: 94.0555733333333,
    inp: {
      config: {
        trial: 100,
        turn: 1500
      },
      friends: [
        {
          double_speed: true,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 6,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 30,
          name: 'ホイミスライム',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 30,
          name: 'スモールグール',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: true,
          hp_dope: 0,
          lv: 30,
          name: 'ホイミスライム',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        }
      ],
      map: {
        col: 10,
        data: [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          0,
          19,
          0,
          1,
          0,
          1,
          1,
          1,
          1,
          1,
          10,
          11,
          12,
          13,
          14,
          1,
          1,
          1,
          1,
          1,
          9,
          9,
          9,
          9,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          15,
          16,
          17,
          18,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        row: 10
      }
    },
    lv_kinoko: 0,
    lv_kiton: 0,
    num_hoimi_slime: 2,
    num_killer_machine: 7,
    stopped_by_enemy_genocide: 0,
    stopped_by_friend_kill: 0,
    turn_passed: 100,
    userid: 'jhOByTg5QfWbuon3iQ3a09k6hO33',
    username: '怒りの',
    with_kinoko: false,
    with_kiton: false
  }
}
