export const sample_inputs = {
  "4キラーマ等速": {
    friends: [
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 6,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 6,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 6,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 6,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "ホイミスライム",
        lv: 30,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "スモールグール",
        lv: 30,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "ホイミスライム",
        lv: 30,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
    ],
    map: {
      row: 10,
      col: 10,
      data: [
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  0,  1,  1,  1,
        1,  1,  0, 19,  0,  0,  0,  1,  1,  1,
        1,  1, 10, 11, 12, 13, 14,  1,  1,  1,
        1,  1,  9,  9,  9,  9,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  1,  1,  1,  1,
        1,  1, 15, 16, 17, 18,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
      ]
    },
    config: {
      turn: 1500,
      trial: 100,
    }
  },
  "4キラーマ倍速": {
    friends: [
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: true,
        hp_dope: 1,
        weaken_atk: 6,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: true,
        hp_dope: 0,
        weaken_atk: 6,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: true,
        hp_dope: 0,
        weaken_atk: 6,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: true,
        hp_dope: 0,
        weaken_atk: 6,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "ホイミスライム",
        lv: 30,
        double_speed: true,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: true,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: true,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: true,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "スモールグール",
        lv: 30,
        double_speed: true,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "ホイミスライム",
        lv: 30,
        double_speed: true,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
    ],
    map: {
      row: 10,
      col: 10,
      data: [
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  0,  1,  1,  1,
        1,  1,  0, 19,  0,  0,  0,  1,  1,  1,
        1,  1, 10, 11, 12, 13, 14,  1,  1,  1,
        1,  1,  9,  9,  9,  9,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  1,  1,  1,  1,
        1,  1, 15, 16, 17, 18,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
      ]
    },
    config: {
      turn: 1500,
      trial: 100,
    }
  },
  "3キラーマ等速": {
    friends: [
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 6,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 6,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 6,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "ホイミスライム",
        lv: 30,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "スモールグール",
        lv: 30,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "ホイミスライム",
        lv: 30,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
    ],
    map: {
      row: 10,
      col: 10,
      data: [
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  1,  1,  1,  1,
        1,  1,  0, 19,  0,  0,  1,  1,  1,  1,
        1,  1, 10, 11, 12, 14,  1,  1,  1,  1,
        1,  1,  0,  0,  9,  1,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  1,  1,  1,  1,  1,
        1,  1, 15, 16, 17,  1,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  1,  1,  1,  1,  1,
        1,  1, 13, 18,  0,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
      ]
    },
    config: {
      turn: 1500,
      trial: 100,
    }
  },
  "キノコtest": {
    friends: [
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 6,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 6,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 6,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "ホイミスライム",
        lv: 30,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "キラーマシン",
        lv: 13,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "おばけキノコ",
        lv: 20,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "スモールグール",
        lv: 30,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
      {
        name: "ホイミスライム",
        lv: 30,
        double_speed: false,
        hp_dope: 0,
        weaken_atk: 0,
        weaken_def: 0,
        sealed: false,
      },
    ],
    map: {
      row: 10,
      col: 10,
      data: [
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  0,  1,  1,  1,  1,
        1,  1,  0, 19,  0,  0,  1,  1,  1,  1,
        1,  1, 10, 11, 12, 14,  1,  1,  1,  1,
        1,  1,  0,  0,  9,  1,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  1,  1,  1,  1,  1,
        1,  1, 15, 16, 17,  1,  1,  1,  1,  1,
        1,  1,  0,  0,  0,  1,  1,  1,  1,  1,
        1,  1, 13, 18,  0,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
      ]
    },
    config: {
      turn: 1500,
      trial: 100,
    }
  },
};
