import run_scs from './run_scs';
import { sample_inputs } from './sample_inputs';

const inp = {
      config: {
        trial: 100,
        turn: 1500
      },
      friends: [
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 5,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 5,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 5,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 30,
          name: 'ホイミスライム',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 13,
          name: 'キラーマシン',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 30,
          name: 'スモールグール',
          sealed: false,
          weaken_atk: 4,
          weaken_def: 0
        },
        {
          double_speed: false,
          hp_dope: 0,
          lv: 30,
          name: 'ホイミスライム',
          sealed: false,
          weaken_atk: 0,
          weaken_def: 0
        }
      ],
      map: {
        col: 12,
        data: [
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          0,
          0,
          9,
          1,
          9,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          0,
          0,
          18,
          19,
          10,
          0,
          0,
          0,
          15,
          1,
          1,
          1,
          0,
          0,
          17,
          14,
          11,
          0,
          0,
          0,
          16,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          12,
          0,
          0,
          0,
          13,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          0,
          0,
          0,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1,
          1
        ],
        row: 12
      }
    }
  


const json = run_scs(inp);

console.log(json);
